{
  "masterWorld": {
    "world": "master_world"
  },
  "baseDecayProbability": 0.5,
  "timeBetweenDecay": 86400,
  "maxDecayTime": 2592000,
  "decayTimeBlockBreak":3600,
  "decayTimeBlockPlace":86400,
  "maxDecayPerTick": 10,
  "claimRadius":16,
  "claimTime":8035200,
  "claimCost":64,
  "blocksDecayProbability": {
    "DIRT": 1,
    "COBBLESTONE": 1,
    "GRASS": 1,
    "WATER": 1,
    "CHEST": 0
  }
}